// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: GradientAIService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package genaimodelcatalog github.com/digitalocean/godo GradientAIService
//

// Package genaimodelcatalog is a generated GoMock package.
package genaimodelcatalog

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockGradientAIService is a mock of GradientAIService interface.
type MockGradientAIService struct {
	ctrl     *gomock.Controller
	recorder *MockGradientAIServiceMockRecorder
	isgomock struct{}
}

// MockGradientAIServiceMockRecorder is the mock recorder for MockGradientAIService.
type MockGradientAIServiceMockRecorder struct {
	mock *MockGradientAIService
}

// NewMockGradientAIService creates a new mock instance.
func NewMockGradientAIService(ctrl *gomock.Controller) *MockGradientAIService {
	mock := &MockGradientAIService{ctrl: ctrl}
	mock.recorder = &MockGradientAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradientAIService) EXPECT() *MockGradientAIServiceMockRecorder {
	return m.recorder
}

// AddAgentRoute mocks base method.
func (m *MockGradientAIService) AddAgentRoute(arg0 context.Context, arg1, arg2 string, arg3 *godo.AgentRouteCreateRequest) (*godo.AgentRouteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgentRoute", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.AgentRouteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddAgentRoute indicates an expected call of AddAgentRoute.
func (mr *MockGradientAIServiceMockRecorder) AddAgentRoute(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentRoute", reflect.TypeOf((*MockGradientAIService)(nil).AddAgentRoute), arg0, arg1, arg2, arg3)
}

// AddKnowledgeBaseDataSource mocks base method.
func (m *MockGradientAIService) AddKnowledgeBaseDataSource(ctx context.Context, knowledgeBaseID string, addDataSource *godo.AddKnowledgeBaseDataSourceRequest) (*godo.KnowledgeBaseDataSource, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKnowledgeBaseDataSource", ctx, knowledgeBaseID, addDataSource)
	ret0, _ := ret[0].(*godo.KnowledgeBaseDataSource)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddKnowledgeBaseDataSource indicates an expected call of AddKnowledgeBaseDataSource.
func (mr *MockGradientAIServiceMockRecorder) AddKnowledgeBaseDataSource(ctx, knowledgeBaseID, addDataSource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKnowledgeBaseDataSource", reflect.TypeOf((*MockGradientAIService)(nil).AddKnowledgeBaseDataSource), ctx, knowledgeBaseID, addDataSource)
}

// AttachKnowledgeBaseToAgent mocks base method.
func (m *MockGradientAIService) AttachKnowledgeBaseToAgent(ctx context.Context, agentID, knowledgeBaseID string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachKnowledgeBaseToAgent", ctx, agentID, knowledgeBaseID)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AttachKnowledgeBaseToAgent indicates an expected call of AttachKnowledgeBaseToAgent.
func (mr *MockGradientAIServiceMockRecorder) AttachKnowledgeBaseToAgent(ctx, agentID, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachKnowledgeBaseToAgent", reflect.TypeOf((*MockGradientAIService)(nil).AttachKnowledgeBaseToAgent), ctx, agentID, knowledgeBaseID)
}

// CancelIndexingJob mocks base method.
func (m *MockGradientAIService) CancelIndexingJob(ctx context.Context, indexingJobUUID string) (*godo.IndexingJobResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelIndexingJob", ctx, indexingJobUUID)
	ret0, _ := ret[0].(*godo.IndexingJobResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CancelIndexingJob indicates an expected call of CancelIndexingJob.
func (mr *MockGradientAIServiceMockRecorder) CancelIndexingJob(ctx, indexingJobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelIndexingJob", reflect.TypeOf((*MockGradientAIService)(nil).CancelIndexingJob), ctx, indexingJobUUID)
}

// CreateAgent mocks base method.
func (m *MockGradientAIService) CreateAgent(arg0 context.Context, arg1 *godo.AgentCreateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", arg0, arg1)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockGradientAIServiceMockRecorder) CreateAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockGradientAIService)(nil).CreateAgent), arg0, arg1)
}

// CreateAgentAPIKey mocks base method.
func (m *MockGradientAIService) CreateAgentAPIKey(arg0 context.Context, arg1 string, arg2 *godo.AgentAPIKeyCreateRequest) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgentAPIKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAgentAPIKey indicates an expected call of CreateAgentAPIKey.
func (mr *MockGradientAIServiceMockRecorder) CreateAgentAPIKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgentAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).CreateAgentAPIKey), arg0, arg1, arg2)
}

// CreateAnthropicAPIKey mocks base method.
func (m *MockGradientAIService) CreateAnthropicAPIKey(ctx context.Context, anthropicAPIKeyCreateRequest *godo.AnthropicAPIKeyCreateRequest) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnthropicAPIKey", ctx, anthropicAPIKeyCreateRequest)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAnthropicAPIKey indicates an expected call of CreateAnthropicAPIKey.
func (mr *MockGradientAIServiceMockRecorder) CreateAnthropicAPIKey(ctx, anthropicAPIKeyCreateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnthropicAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).CreateAnthropicAPIKey), ctx, anthropicAPIKeyCreateRequest)
}

// CreateFunctionRoute mocks base method.
func (m *MockGradientAIService) CreateFunctionRoute(arg0 context.Context, arg1 string, arg2 *godo.FunctionRouteCreateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFunctionRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateFunctionRoute indicates an expected call of CreateFunctionRoute.
func (mr *MockGradientAIServiceMockRecorder) CreateFunctionRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFunctionRoute", reflect.TypeOf((*MockGradientAIService)(nil).CreateFunctionRoute), arg0, arg1, arg2)
}

// CreateKnowledgeBase mocks base method.
func (m *MockGradientAIService) CreateKnowledgeBase(ctx context.Context, knowledgeBaseCreate *godo.KnowledgeBaseCreateRequest) (*godo.KnowledgeBase, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeBase", ctx, knowledgeBaseCreate)
	ret0, _ := ret[0].(*godo.KnowledgeBase)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateKnowledgeBase indicates an expected call of CreateKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) CreateKnowledgeBase(ctx, knowledgeBaseCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).CreateKnowledgeBase), ctx, knowledgeBaseCreate)
}

// CreateOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) CreateOpenAIAPIKey(ctx context.Context, openaiAPIKeyCreate *godo.OpenAIAPIKeyCreateRequest) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenAIAPIKey", ctx, openaiAPIKeyCreate)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateOpenAIAPIKey indicates an expected call of CreateOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) CreateOpenAIAPIKey(ctx, openaiAPIKeyCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).CreateOpenAIAPIKey), ctx, openaiAPIKeyCreate)
}

// DeleteAgent mocks base method.
func (m *MockGradientAIService) DeleteAgent(arg0 context.Context, arg1 string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgent", arg0, arg1)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAgent indicates an expected call of DeleteAgent.
func (mr *MockGradientAIServiceMockRecorder) DeleteAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgent", reflect.TypeOf((*MockGradientAIService)(nil).DeleteAgent), arg0, arg1)
}

// DeleteAgentAPIKey mocks base method.
func (m *MockGradientAIService) DeleteAgentAPIKey(arg0 context.Context, arg1, arg2 string) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentAPIKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAgentAPIKey indicates an expected call of DeleteAgentAPIKey.
func (mr *MockGradientAIServiceMockRecorder) DeleteAgentAPIKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).DeleteAgentAPIKey), arg0, arg1, arg2)
}

// DeleteAgentRoute mocks base method.
func (m *MockGradientAIService) DeleteAgentRoute(arg0 context.Context, arg1, arg2 string) (*godo.AgentRouteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgentRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.AgentRouteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAgentRoute indicates an expected call of DeleteAgentRoute.
func (mr *MockGradientAIServiceMockRecorder) DeleteAgentRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgentRoute", reflect.TypeOf((*MockGradientAIService)(nil).DeleteAgentRoute), arg0, arg1, arg2)
}

// DeleteAnthropicAPIKey mocks base method.
func (m *MockGradientAIService) DeleteAnthropicAPIKey(ctx context.Context, id string) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnthropicAPIKey", ctx, id)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAnthropicAPIKey indicates an expected call of DeleteAnthropicAPIKey.
func (mr *MockGradientAIServiceMockRecorder) DeleteAnthropicAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnthropicAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).DeleteAnthropicAPIKey), ctx, id)
}

// DeleteFunctionRoute mocks base method.
func (m *MockGradientAIService) DeleteFunctionRoute(arg0 context.Context, arg1, arg2 string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFunctionRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteFunctionRoute indicates an expected call of DeleteFunctionRoute.
func (mr *MockGradientAIServiceMockRecorder) DeleteFunctionRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFunctionRoute", reflect.TypeOf((*MockGradientAIService)(nil).DeleteFunctionRoute), arg0, arg1, arg2)
}

// DeleteKnowledgeBase mocks base method.
func (m *MockGradientAIService) DeleteKnowledgeBase(ctx context.Context, knowledgeBaseID string) (string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBase", ctx, knowledgeBaseID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteKnowledgeBase indicates an expected call of DeleteKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) DeleteKnowledgeBase(ctx, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).DeleteKnowledgeBase), ctx, knowledgeBaseID)
}

// DeleteKnowledgeBaseDataSource mocks base method.
func (m *MockGradientAIService) DeleteKnowledgeBaseDataSource(ctx context.Context, knowledgeBaseID, dataSourceID string) (string, string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBaseDataSource", ctx, knowledgeBaseID, dataSourceID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*godo.Response)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DeleteKnowledgeBaseDataSource indicates an expected call of DeleteKnowledgeBaseDataSource.
func (mr *MockGradientAIServiceMockRecorder) DeleteKnowledgeBaseDataSource(ctx, knowledgeBaseID, dataSourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBaseDataSource", reflect.TypeOf((*MockGradientAIService)(nil).DeleteKnowledgeBaseDataSource), ctx, knowledgeBaseID, dataSourceID)
}

// DeleteOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) DeleteOpenAIAPIKey(ctx context.Context, openaiApiKeyId string) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpenAIAPIKey", ctx, openaiApiKeyId)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteOpenAIAPIKey indicates an expected call of DeleteOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) DeleteOpenAIAPIKey(ctx, openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).DeleteOpenAIAPIKey), ctx, openaiApiKeyId)
}

// DetachKnowledgeBaseToAgent mocks base method.
func (m *MockGradientAIService) DetachKnowledgeBaseToAgent(ctx context.Context, agentID, knowledgeBaseID string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachKnowledgeBaseToAgent", ctx, agentID, knowledgeBaseID)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DetachKnowledgeBaseToAgent indicates an expected call of DetachKnowledgeBaseToAgent.
func (mr *MockGradientAIServiceMockRecorder) DetachKnowledgeBaseToAgent(ctx, agentID, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachKnowledgeBaseToAgent", reflect.TypeOf((*MockGradientAIService)(nil).DetachKnowledgeBaseToAgent), ctx, agentID, knowledgeBaseID)
}

// GetAgent mocks base method.
func (m *MockGradientAIService) GetAgent(arg0 context.Context, arg1 string) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0, arg1)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockGradientAIServiceMockRecorder) GetAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockGradientAIService)(nil).GetAgent), arg0, arg1)
}

// GetAnthropicAPIKey mocks base method.
func (m *MockGradientAIService) GetAnthropicAPIKey(ctx context.Context, id string) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnthropicAPIKey", ctx, id)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAnthropicAPIKey indicates an expected call of GetAnthropicAPIKey.
func (mr *MockGradientAIServiceMockRecorder) GetAnthropicAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnthropicAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).GetAnthropicAPIKey), ctx, id)
}

// GetIndexingJob mocks base method.
func (m *MockGradientAIService) GetIndexingJob(ctx context.Context, indexingJobUUID string) (*godo.IndexingJobResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexingJob", ctx, indexingJobUUID)
	ret0, _ := ret[0].(*godo.IndexingJobResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIndexingJob indicates an expected call of GetIndexingJob.
func (mr *MockGradientAIServiceMockRecorder) GetIndexingJob(ctx, indexingJobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexingJob", reflect.TypeOf((*MockGradientAIService)(nil).GetIndexingJob), ctx, indexingJobUUID)
}

// GetKnowledgeBase mocks base method.
func (m *MockGradientAIService) GetKnowledgeBase(ctx context.Context, knowledgeBaseID string) (*godo.KnowledgeBase, string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase", ctx, knowledgeBaseID)
	ret0, _ := ret[0].(*godo.KnowledgeBase)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*godo.Response)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) GetKnowledgeBase(ctx, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).GetKnowledgeBase), ctx, knowledgeBaseID)
}

// GetModelByUUID mocks base method.
func (m *MockGradientAIService) GetModelByUUID(arg0 context.Context, arg1 string) (*godo.Model, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByUUID", arg0, arg1)
	ret0, _ := ret[0].(*godo.Model)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetModelByUUID indicates an expected call of GetModelByUUID.
func (mr *MockGradientAIServiceMockRecorder) GetModelByUUID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByUUID", reflect.TypeOf((*MockGradientAIService)(nil).GetModelByUUID), arg0, arg1)
}

// GetOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) GetOpenAIAPIKey(ctx context.Context, openaiApiKeyId string) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenAIAPIKey", ctx, openaiApiKeyId)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOpenAIAPIKey indicates an expected call of GetOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) GetOpenAIAPIKey(ctx, openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).GetOpenAIAPIKey), ctx, openaiApiKeyId)
}

// ListAgentAPIKeys mocks base method.
func (m *MockGradientAIService) ListAgentAPIKeys(arg0 context.Context, arg1 string, arg2 *godo.ListOptions) ([]*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentAPIKeys", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentAPIKeys indicates an expected call of ListAgentAPIKeys.
func (mr *MockGradientAIServiceMockRecorder) ListAgentAPIKeys(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentAPIKeys", reflect.TypeOf((*MockGradientAIService)(nil).ListAgentAPIKeys), arg0, arg1, arg2)
}

// ListAgentVersions mocks base method.
func (m *MockGradientAIService) ListAgentVersions(arg0 context.Context, arg1 string, arg2 *godo.ListOptions) ([]*godo.AgentVersion, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentVersions", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.AgentVersion)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentVersions indicates an expected call of ListAgentVersions.
func (mr *MockGradientAIServiceMockRecorder) ListAgentVersions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentVersions", reflect.TypeOf((*MockGradientAIService)(nil).ListAgentVersions), arg0, arg1, arg2)
}

// ListAgents mocks base method.
func (m *MockGradientAIService) ListAgents(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", arg0, arg1)
	ret0, _ := ret[0].([]*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockGradientAIServiceMockRecorder) ListAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockGradientAIService)(nil).ListAgents), arg0, arg1)
}

// ListAgentsByAnthropicAPIKey mocks base method.
func (m *MockGradientAIService) ListAgentsByAnthropicAPIKey(ctx context.Context, id string, opt *godo.ListOptions) ([]*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByAnthropicAPIKey", ctx, id, opt)
	ret0, _ := ret[0].([]*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentsByAnthropicAPIKey indicates an expected call of ListAgentsByAnthropicAPIKey.
func (mr *MockGradientAIServiceMockRecorder) ListAgentsByAnthropicAPIKey(ctx, id, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByAnthropicAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).ListAgentsByAnthropicAPIKey), ctx, id, opt)
}

// ListAgentsByOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) ListAgentsByOpenAIAPIKey(ctx context.Context, openaiApiKeyId string, opt *godo.ListOptions) ([]*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByOpenAIAPIKey", ctx, openaiApiKeyId, opt)
	ret0, _ := ret[0].([]*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgentsByOpenAIAPIKey indicates an expected call of ListAgentsByOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) ListAgentsByOpenAIAPIKey(ctx, openaiApiKeyId, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).ListAgentsByOpenAIAPIKey), ctx, openaiApiKeyId, opt)
}

// ListAnthropicAPIKeys mocks base method.
func (m *MockGradientAIService) ListAnthropicAPIKeys(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnthropicAPIKeys", arg0, arg1)
	ret0, _ := ret[0].([]*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAnthropicAPIKeys indicates an expected call of ListAnthropicAPIKeys.
func (mr *MockGradientAIServiceMockRecorder) ListAnthropicAPIKeys(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnthropicAPIKeys", reflect.TypeOf((*MockGradientAIService)(nil).ListAnthropicAPIKeys), arg0, arg1)
}

// ListAvailableModels mocks base method.
func (m *MockGradientAIService) ListAvailableModels(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.Model, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableModels", arg0, arg1)
	ret0, _ := ret[0].([]*godo.Model)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAvailableModels indicates an expected call of ListAvailableModels.
func (mr *MockGradientAIServiceMockRecorder) ListAvailableModels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableModels", reflect.TypeOf((*MockGradientAIService)(nil).ListAvailableModels), arg0, arg1)
}

// ListDatacenterRegions mocks base method.
func (m *MockGradientAIService) ListDatacenterRegions(arg0 context.Context, arg1, arg2 *bool) ([]*godo.DatacenterRegions, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDatacenterRegions", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.DatacenterRegions)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDatacenterRegions indicates an expected call of ListDatacenterRegions.
func (mr *MockGradientAIServiceMockRecorder) ListDatacenterRegions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatacenterRegions", reflect.TypeOf((*MockGradientAIService)(nil).ListDatacenterRegions), arg0, arg1, arg2)
}

// ListIndexingJobDataSources mocks base method.
func (m *MockGradientAIService) ListIndexingJobDataSources(ctx context.Context, indexingJobUUID string) (*godo.IndexingJobDataSourcesResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobDataSources", ctx, indexingJobUUID)
	ret0, _ := ret[0].(*godo.IndexingJobDataSourcesResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListIndexingJobDataSources indicates an expected call of ListIndexingJobDataSources.
func (mr *MockGradientAIServiceMockRecorder) ListIndexingJobDataSources(ctx, indexingJobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobDataSources", reflect.TypeOf((*MockGradientAIService)(nil).ListIndexingJobDataSources), ctx, indexingJobUUID)
}

// ListIndexingJobs mocks base method.
func (m *MockGradientAIService) ListIndexingJobs(ctx context.Context, opt *godo.ListOptions) (*godo.IndexingJobsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobs", ctx, opt)
	ret0, _ := ret[0].(*godo.IndexingJobsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListIndexingJobs indicates an expected call of ListIndexingJobs.
func (mr *MockGradientAIServiceMockRecorder) ListIndexingJobs(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobs", reflect.TypeOf((*MockGradientAIService)(nil).ListIndexingJobs), ctx, opt)
}

// ListKnowledgeBaseDataSources mocks base method.
func (m *MockGradientAIService) ListKnowledgeBaseDataSources(ctx context.Context, knowledgeBaseID string, opt *godo.ListOptions) ([]godo.KnowledgeBaseDataSource, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBaseDataSources", ctx, knowledgeBaseID, opt)
	ret0, _ := ret[0].([]godo.KnowledgeBaseDataSource)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListKnowledgeBaseDataSources indicates an expected call of ListKnowledgeBaseDataSources.
func (mr *MockGradientAIServiceMockRecorder) ListKnowledgeBaseDataSources(ctx, knowledgeBaseID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBaseDataSources", reflect.TypeOf((*MockGradientAIService)(nil).ListKnowledgeBaseDataSources), ctx, knowledgeBaseID, opt)
}

// ListKnowledgeBases mocks base method.
func (m *MockGradientAIService) ListKnowledgeBases(ctx context.Context, opt *godo.ListOptions) ([]godo.KnowledgeBase, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBases", ctx, opt)
	ret0, _ := ret[0].([]godo.KnowledgeBase)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListKnowledgeBases indicates an expected call of ListKnowledgeBases.
func (mr *MockGradientAIServiceMockRecorder) ListKnowledgeBases(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBases", reflect.TypeOf((*MockGradientAIService)(nil).ListKnowledgeBases), ctx, opt)
}

// ListOpenAIAPIKeys mocks base method.
func (m *MockGradientAIService) ListOpenAIAPIKeys(arg0 context.Context, arg1 *godo.ListOptions) ([]*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenAIAPIKeys", arg0, arg1)
	ret0, _ := ret[0].([]*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOpenAIAPIKeys indicates an expected call of ListOpenAIAPIKeys.
func (mr *MockGradientAIServiceMockRecorder) ListOpenAIAPIKeys(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenAIAPIKeys", reflect.TypeOf((*MockGradientAIService)(nil).ListOpenAIAPIKeys), arg0, arg1)
}

// RegenerateAgentAPIKey mocks base method.
func (m *MockGradientAIService) RegenerateAgentAPIKey(arg0 context.Context, arg1, arg2 string) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegenerateAgentAPIKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RegenerateAgentAPIKey indicates an expected call of RegenerateAgentAPIKey.
func (mr *MockGradientAIServiceMockRecorder) RegenerateAgentAPIKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateAgentAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).RegenerateAgentAPIKey), arg0, arg1, arg2)
}

// RollbackAgentVersion mocks base method.
func (m *MockGradientAIService) RollbackAgentVersion(arg0 context.Context, arg1, arg2 string) (string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackAgentVersion", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RollbackAgentVersion indicates an expected call of RollbackAgentVersion.
func (mr *MockGradientAIServiceMockRecorder) RollbackAgentVersion(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackAgentVersion", reflect.TypeOf((*MockGradientAIService)(nil).RollbackAgentVersion), arg0, arg1, arg2)
}

// SearchModels mocks base method.
func (m *MockGradientAIService) SearchModels(arg0 context.Context, arg1 string) ([]string, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchModels", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchModels indicates an expected call of SearchModels.
func (mr *MockGradientAIServiceMockRecorder) SearchModels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchModels", reflect.TypeOf((*MockGradientAIService)(nil).SearchModels), arg0, arg1)
}

// UpdateAgent mocks base method.
func (m *MockGradientAIService) UpdateAgent(arg0 context.Context, arg1 string, arg2 *godo.AgentUpdateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgent indicates an expected call of UpdateAgent.
func (mr *MockGradientAIServiceMockRecorder) UpdateAgent(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgent", reflect.TypeOf((*MockGradientAIService)(nil).UpdateAgent), arg0, arg1, arg2)
}

// UpdateAgentAPIKey mocks base method.
func (m *MockGradientAIService) UpdateAgentAPIKey(arg0 context.Context, arg1, arg2 string, arg3 *godo.AgentAPIKeyUpdateRequest) (*godo.ApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentAPIKey", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.ApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgentAPIKey indicates an expected call of UpdateAgentAPIKey.
func (mr *MockGradientAIServiceMockRecorder) UpdateAgentAPIKey(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).UpdateAgentAPIKey), arg0, arg1, arg2, arg3)
}

// UpdateAgentRoute mocks base method.
func (m *MockGradientAIService) UpdateAgentRoute(arg0 context.Context, arg1, arg2 string, arg3 *godo.AgentRouteUpdateRequest) (*godo.AgentRouteResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentRoute", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.AgentRouteResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgentRoute indicates an expected call of UpdateAgentRoute.
func (mr *MockGradientAIServiceMockRecorder) UpdateAgentRoute(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentRoute", reflect.TypeOf((*MockGradientAIService)(nil).UpdateAgentRoute), arg0, arg1, arg2, arg3)
}

// UpdateAgentVisibility mocks base method.
func (m *MockGradientAIService) UpdateAgentVisibility(arg0 context.Context, arg1 string, arg2 *godo.AgentVisibilityUpdateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentVisibility", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAgentVisibility indicates an expected call of UpdateAgentVisibility.
func (mr *MockGradientAIServiceMockRecorder) UpdateAgentVisibility(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentVisibility", reflect.TypeOf((*MockGradientAIService)(nil).UpdateAgentVisibility), arg0, arg1, arg2)
}

// UpdateAnthropicAPIKey mocks base method.
func (m *MockGradientAIService) UpdateAnthropicAPIKey(ctx context.Context, id string, anthropicAPIKeyUpdateRequest *godo.AnthropicAPIKeyUpdateRequest) (*godo.AnthropicApiKeyInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnthropicAPIKey", ctx, id, anthropicAPIKeyUpdateRequest)
	ret0, _ := ret[0].(*godo.AnthropicApiKeyInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateAnthropicAPIKey indicates an expected call of UpdateAnthropicAPIKey.
func (mr *MockGradientAIServiceMockRecorder) UpdateAnthropicAPIKey(ctx, id, anthropicAPIKeyUpdateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnthropicAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).UpdateAnthropicAPIKey), ctx, id, anthropicAPIKeyUpdateRequest)
}

// UpdateFunctionRoute mocks base method.
func (m *MockGradientAIService) UpdateFunctionRoute(arg0 context.Context, arg1, arg2 string, arg3 *godo.FunctionRouteUpdateRequest) (*godo.Agent, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFunctionRoute", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.Agent)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateFunctionRoute indicates an expected call of UpdateFunctionRoute.
func (mr *MockGradientAIServiceMockRecorder) UpdateFunctionRoute(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFunctionRoute", reflect.TypeOf((*MockGradientAIService)(nil).UpdateFunctionRoute), arg0, arg1, arg2, arg3)
}

// UpdateKnowledgeBase mocks base method.
func (m *MockGradientAIService) UpdateKnowledgeBase(ctx context.Context, knowledgeBaseID string, update *godo.UpdateKnowledgeBaseRequest) (*godo.KnowledgeBase, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBase", ctx, knowledgeBaseID, update)
	ret0, _ := ret[0].(*godo.KnowledgeBase)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateKnowledgeBase indicates an expected call of UpdateKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) UpdateKnowledgeBase(ctx, knowledgeBaseID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).UpdateKnowledgeBase), ctx, knowledgeBaseID, update)
}

// UpdateOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) UpdateOpenAIAPIKey(ctx context.Context, openaiApiKeyId string, openaiAPIKeyUpdate *godo.OpenAIAPIKeyUpdateRequest) (*godo.OpenAiApiKey, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOpenAIAPIKey", ctx, openaiApiKeyId, openaiAPIKeyUpdate)
	ret0, _ := ret[0].(*godo.OpenAiApiKey)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateOpenAIAPIKey indicates an expected call of UpdateOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) UpdateOpenAIAPIKey(ctx, openaiApiKeyId, openaiAPIKeyUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).UpdateOpenAIAPIKey), ctx, openaiApiKeyId, openaiAPIKeyUpdate)
}
