// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: NfsService,NfsActionsService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package nfs github.com/digitalocean/godo NfsService,NfsActionsService
//

// Package nfs is a generated GoMock package.
package nfs

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockNfsService is a mock of NfsService interface.
type MockNfsService struct {
	ctrl     *gomock.Controller
	recorder *MockNfsServiceMockRecorder
	isgomock struct{}
}

// MockNfsServiceMockRecorder is the mock recorder for MockNfsService.
type MockNfsServiceMockRecorder struct {
	mock *MockNfsService
}

// NewMockNfsService creates a new mock instance.
func NewMockNfsService(ctrl *gomock.Controller) *MockNfsService {
	mock := &MockNfsService{ctrl: ctrl}
	mock.recorder = &MockNfsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNfsService) EXPECT() *MockNfsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNfsService) Create(ctx context.Context, nfsCreateRequest *godo.NfsCreateRequest) (*godo.Nfs, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, nfsCreateRequest)
	ret0, _ := ret[0].(*godo.Nfs)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockNfsServiceMockRecorder) Create(ctx, nfsCreateRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNfsService)(nil).Create), ctx, nfsCreateRequest)
}

// CreateAccessPoint mocks base method.
func (m *MockNfsService) CreateAccessPoint(ctx context.Context, shareID string, createRequest *godo.NfsCreateAccessPointRequest) (*godo.NfsAccessPointActionResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPoint", ctx, shareID, createRequest)
	ret0, _ := ret[0].(*godo.NfsAccessPointActionResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAccessPoint indicates an expected call of CreateAccessPoint.
func (mr *MockNfsServiceMockRecorder) CreateAccessPoint(ctx, shareID, createRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPoint", reflect.TypeOf((*MockNfsService)(nil).CreateAccessPoint), ctx, shareID, createRequest)
}

// Delete mocks base method.
func (m *MockNfsService) Delete(ctx context.Context, nfsShareId, region string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, nfsShareId, region)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNfsServiceMockRecorder) Delete(ctx, nfsShareId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNfsService)(nil).Delete), ctx, nfsShareId, region)
}

// DeleteAccessPoint mocks base method.
func (m *MockNfsService) DeleteAccessPoint(ctx context.Context, accessPointID string) (*godo.NfsAccessPointActionResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPoint", ctx, accessPointID)
	ret0, _ := ret[0].(*godo.NfsAccessPointActionResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteAccessPoint indicates an expected call of DeleteAccessPoint.
func (mr *MockNfsServiceMockRecorder) DeleteAccessPoint(ctx, accessPointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPoint", reflect.TypeOf((*MockNfsService)(nil).DeleteAccessPoint), ctx, accessPointID)
}

// DeleteSnapshot mocks base method.
func (m *MockNfsService) DeleteSnapshot(ctx context.Context, nfsSnapshotID, region string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", ctx, nfsSnapshotID, region)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockNfsServiceMockRecorder) DeleteSnapshot(ctx, nfsSnapshotID, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockNfsService)(nil).DeleteSnapshot), ctx, nfsSnapshotID, region)
}

// Get mocks base method.
func (m *MockNfsService) Get(ctx context.Context, nfsShareId, region string) (*godo.Nfs, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, nfsShareId, region)
	ret0, _ := ret[0].(*godo.Nfs)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockNfsServiceMockRecorder) Get(ctx, nfsShareId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNfsService)(nil).Get), ctx, nfsShareId, region)
}

// GetAccessPoint mocks base method.
func (m *MockNfsService) GetAccessPoint(ctx context.Context, accessPointID string) (*godo.NfsAccessPoint, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessPoint", ctx, accessPointID)
	ret0, _ := ret[0].(*godo.NfsAccessPoint)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccessPoint indicates an expected call of GetAccessPoint.
func (mr *MockNfsServiceMockRecorder) GetAccessPoint(ctx, accessPointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessPoint", reflect.TypeOf((*MockNfsService)(nil).GetAccessPoint), ctx, accessPointID)
}

// GetSnapshot mocks base method.
func (m *MockNfsService) GetSnapshot(ctx context.Context, nfsSnapshotID, region string) (*godo.NfsSnapshot, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot", ctx, nfsSnapshotID, region)
	ret0, _ := ret[0].(*godo.NfsSnapshot)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockNfsServiceMockRecorder) GetSnapshot(ctx, nfsSnapshotID, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockNfsService)(nil).GetSnapshot), ctx, nfsSnapshotID, region)
}

// List mocks base method.
func (m *MockNfsService) List(ctx context.Context, opts *godo.ListOptions, region string) ([]*godo.Nfs, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts, region)
	ret0, _ := ret[0].([]*godo.Nfs)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockNfsServiceMockRecorder) List(ctx, opts, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNfsService)(nil).List), ctx, opts, region)
}

// ListAccessPoints mocks base method.
func (m *MockNfsService) ListAccessPoints(ctx context.Context, shareID string, opts *godo.NfsListAccessPointsOptions) ([]*godo.NfsAccessPoint, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessPoints", ctx, shareID, opts)
	ret0, _ := ret[0].([]*godo.NfsAccessPoint)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAccessPoints indicates an expected call of ListAccessPoints.
func (mr *MockNfsServiceMockRecorder) ListAccessPoints(ctx, shareID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessPoints", reflect.TypeOf((*MockNfsService)(nil).ListAccessPoints), ctx, shareID, opts)
}

// ListSnapshots mocks base method.
func (m *MockNfsService) ListSnapshots(ctx context.Context, opts *godo.ListOptions, nfsShareId, region string) ([]*godo.NfsSnapshot, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshots", ctx, opts, nfsShareId, region)
	ret0, _ := ret[0].([]*godo.NfsSnapshot)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockNfsServiceMockRecorder) ListSnapshots(ctx, opts, nfsShareId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshots", reflect.TypeOf((*MockNfsService)(nil).ListSnapshots), ctx, opts, nfsShareId, region)
}

// MockNfsActionsService is a mock of NfsActionsService interface.
type MockNfsActionsService struct {
	ctrl     *gomock.Controller
	recorder *MockNfsActionsServiceMockRecorder
	isgomock struct{}
}

// MockNfsActionsServiceMockRecorder is the mock recorder for MockNfsActionsService.
type MockNfsActionsServiceMockRecorder struct {
	mock *MockNfsActionsService
}

// NewMockNfsActionsService creates a new mock instance.
func NewMockNfsActionsService(ctrl *gomock.Controller) *MockNfsActionsService {
	mock := &MockNfsActionsService{ctrl: ctrl}
	mock.recorder = &MockNfsActionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNfsActionsService) EXPECT() *MockNfsActionsServiceMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockNfsActionsService) Attach(ctx context.Context, nfsShareId, vpcID, region string) (*godo.NfsAction, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, nfsShareId, vpcID, region)
	ret0, _ := ret[0].(*godo.NfsAction)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Attach indicates an expected call of Attach.
func (mr *MockNfsActionsServiceMockRecorder) Attach(ctx, nfsShareId, vpcID, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockNfsActionsService)(nil).Attach), ctx, nfsShareId, vpcID, region)
}

// Detach mocks base method.
func (m *MockNfsActionsService) Detach(ctx context.Context, nfsShareId, vpcID, region string) (*godo.NfsAction, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", ctx, nfsShareId, vpcID, region)
	ret0, _ := ret[0].(*godo.NfsAction)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Detach indicates an expected call of Detach.
func (mr *MockNfsActionsServiceMockRecorder) Detach(ctx, nfsShareId, vpcID, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockNfsActionsService)(nil).Detach), ctx, nfsShareId, vpcID, region)
}

// Reassign mocks base method.
func (m *MockNfsActionsService) Reassign(ctx context.Context, nfsShareId, oldVpcID, newVpcID string) (*godo.NfsAction, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reassign", ctx, nfsShareId, oldVpcID, newVpcID)
	ret0, _ := ret[0].(*godo.NfsAction)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Reassign indicates an expected call of Reassign.
func (mr *MockNfsActionsServiceMockRecorder) Reassign(ctx, nfsShareId, oldVpcID, newVpcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reassign", reflect.TypeOf((*MockNfsActionsService)(nil).Reassign), ctx, nfsShareId, oldVpcID, newVpcID)
}

// Resize mocks base method.
func (m *MockNfsActionsService) Resize(ctx context.Context, nfsShareId string, size uint64, region string) (*godo.NfsAction, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", ctx, nfsShareId, size, region)
	ret0, _ := ret[0].(*godo.NfsAction)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Resize indicates an expected call of Resize.
func (mr *MockNfsActionsServiceMockRecorder) Resize(ctx, nfsShareId, size, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockNfsActionsService)(nil).Resize), ctx, nfsShareId, size, region)
}

// Snapshot mocks base method.
func (m *MockNfsActionsService) Snapshot(ctx context.Context, nfsShareId, nfsSnapshotName, region string) (*godo.NfsAction, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx, nfsShareId, nfsSnapshotName, region)
	ret0, _ := ret[0].(*godo.NfsAction)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockNfsActionsServiceMockRecorder) Snapshot(ctx, nfsShareId, nfsSnapshotName, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockNfsActionsService)(nil).Snapshot), ctx, nfsShareId, nfsSnapshotName, region)
}

// SwitchPerformanceTier mocks base method.
func (m *MockNfsActionsService) SwitchPerformanceTier(ctx context.Context, nfsShareId, tier string) (*godo.NfsAction, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchPerformanceTier", ctx, nfsShareId, tier)
	ret0, _ := ret[0].(*godo.NfsAction)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SwitchPerformanceTier indicates an expected call of SwitchPerformanceTier.
func (mr *MockNfsActionsServiceMockRecorder) SwitchPerformanceTier(ctx, nfsShareId, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchPerformanceTier", reflect.TypeOf((*MockNfsActionsService)(nil).SwitchPerformanceTier), ctx, nfsShareId, tier)
}
